# Generated by Django 4.2.6 on 2023-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_forget',
            field=models.CharField(blank=True, max_length=50, verbose_name='psdf'),
        ),
    ]
