# Generated by Django 4.2.6 on 2023-10-26 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_for_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=200)),
                ('crypto_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('transaction_mode', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], max_length=11)),
                ('cryptos', models.CharField(default='usdt', max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_trade', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=200)),
                ('crypto_address', models.CharField(max_length=200)),
                ('ammount_in_crypto', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deposite_transact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposite.deposite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund_user_wallet_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('crypto_types', models.CharField(choices=[('xrp', 'XRP'), ('xlm', 'XLM'), ('algo', 'ALGO'), ('cardano', 'CARDANO')], default='xrp', max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
