# Generated by Django 4.2.6 on 2023-10-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0001_initial'),
        ('deposite', '0003_crypto_for_payments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='withdrawal_transact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='withdrawal.withdrawal_transact'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='deposite_transact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deposite.deposite'),
        ),
    ]
